"""Final snapshot with preserved indexes

Revision ID: 664fe1eb25a2
Revises: 6922306136cb
Create Date: 2025-07-22 14:13:39.850083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '664fe1eb25a2'
down_revision: Union[str, None] = '6922306136cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('migration_errors', 'session_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index('idx_migration_errors_created_at', table_name='migration_errors')
    op.drop_index('idx_migration_errors_session_id', table_name='migration_errors')
    op.drop_index('idx_migration_errors_user_id', table_name='migration_errors')
    op.execute("ALTER TABLE refresh_tokens ALTER COLUMN id SET DATA TYPE UUID USING id::uuid")
    op.alter_column('refresh_tokens', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint('refresh_tokens_user_id_fkey', 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key('refresh_tokens_user_id_fkey', 'refresh_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('refresh_tokens', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('refresh_tokens', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.create_index('idx_migration_errors_user_id', 'migration_errors', ['user_id'], unique=False)
    op.create_index('idx_migration_errors_session_id', 'migration_errors', ['session_id'], unique=False)
    op.create_index('idx_migration_errors_created_at', 'migration_errors', ['created_at'], unique=False)
    op.alter_column('migration_errors', 'session_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
