"""test diff from QA

Revision ID: fe265a163605
Revises: 664fe1eb25a2
Create Date: 2025-07-23 14:56:40.128808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe265a163605'
down_revision: Union[str, None] = '664fe1eb25a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('migration_errors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('error_type', sa.String(length=100), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_migration_errors_created_at', 'migration_errors', ['created_at'], unique=False)
    op.create_index('idx_migration_errors_session_id', 'migration_errors', ['session_id'], unique=False)
    op.create_index('idx_migration_errors_user_id', 'migration_errors', ['user_id'], unique=False)
    op.add_column('nodes', sa.Column('is_encrypted', sa.Boolean(), nullable=True))
    op.add_column('reflections', sa.Column('is_encrypted', sa.Boolean(), nullable=True))
    op.alter_column('refresh_tokens', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint('refresh_tokens_user_id_fkey', 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['user_id'], ['id'])
    op.add_column('sessions', sa.Column('is_encrypted', sa.Boolean(), nullable=True))
    op.add_column('user_profiles', sa.Column('tour_completed', sa.Boolean(), nullable=True))
    op.drop_column('user_profiles', 'language_preference')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('language_preference', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('user_profiles', 'tour_completed')
    op.drop_column('sessions', 'is_encrypted')
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key('refresh_tokens_user_id_fkey', 'refresh_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('refresh_tokens', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('refresh_tokens', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('reflections', 'is_encrypted')
    op.drop_column('nodes', 'is_encrypted')
    op.drop_index('idx_migration_errors_user_id', table_name='migration_errors')
    op.drop_index('idx_migration_errors_session_id', table_name='migration_errors')
    op.drop_index('idx_migration_errors_created_at', table_name='migration_errors')
    op.drop_table('migration_errors')
    # ### end Alembic commands ###
